# Generated by Django 4.2.7 on 2023-11-17 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_review_alter_room_roommates'),
        ('review', '0002_alter_propertyreview_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
