# Generated by Django 4.2.7 on 2023-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_studentreview_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rating',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='roommatereview',
            name='rating',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='studentreview',
            name='rating',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
