# Generated by Django 4.2.7 on 2023-11-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_propertyreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommatereview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
