# Generated by Django 4.2.7 on 2023-11-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_roommatereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rating',
            field=models.PositiveIntegerField(verbose_name=range(1, 6)),
        ),
    ]
