# Generated by Django 4.2.7 on 2023-11-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_propertyreview_reviewer_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='reviews',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reviews_by_property_owners',
            field=models.ManyToManyField(blank=True, related_name='student_reviews', to='review.studentreview'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reviews_by_roommates',
            field=models.ManyToManyField(blank=True, related_name='student_reviews', to='review.roommatereview'),
        ),
    ]
