# Generated by Django 4.2.7 on 2023-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentprofile_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_level',
            field=models.CharField(blank=True, help_text='e.g., Freshman, Sophomore, Graduate Student', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cleanliness_level',
            field=models.IntegerField(blank=True, help_text='Rate your cleanliness on a scale of 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, help_text='Your academic major or field of study', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_roommate',
            field=models.TextField(blank=True, help_text="List your preferred roommate's interests, hobbies, and other characteristics", null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pictures/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='smoking_preference',
            field=models.BooleanField(default=False, help_text='Do you prefer a non-smoking environment?'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='List your hobbies and interests', null=True),
        ),
    ]
