# Generated by Django 4.2.7 on 2023-11-17 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownerprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='property_owner_reviews', to='review.roommatereview'),
        ),
        migrations.AddField(
            model_name='propertyownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='property.amenities'),
        ),
        migrations.AddField(
            model_name='property',
            name='images_or_videos',
            field=models.ManyToManyField(blank=True, related_name='property_media', to='property.media'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='property_reviews', to='review.roommatereview'),
        ),
        migrations.AddField(
            model_name='property',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='property_rooms', to='property.room'),
        ),
    ]
