# Generated by Django 4.2.7 on 2023-11-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_roomtype_remove_room_room_count_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertyownerprofile'),
        ),
    ]
