# Generated by Django 4.2.7 on 2023-11-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('review', '0001_initial'),
        ('property', '0004_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='property_reviews', to='review.propertyreview'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roommates',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='student.studentprofile'),
        ),
    ]
