# Generated by Django 4.2.7 on 2023-11-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_review_alter_room_roommates'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Cebu City', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='Philippines', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='Cebu', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='Gorordo Avenue', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(default='6000', max_length=255),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/amenities_icons/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='static/media_files/'),
        ),
    ]
