# Generated by Django 4.2.7 on 2023-11-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_city_property_country_property_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(max_length=255),
        ),
    ]
