# Generated by Django 4.2.6 on 2023-11-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_property_location_alter_property_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.CharField(default='mixed', max_length=255),
        ),
    ]
